### ISSUE TITLE
Support for authentication with channeler

### ISSUE THREAD

**Issue by vrecan** [zeromq/goczmq#135]
Are there plans to support socket options and authentication using channelers? 

Common scenario for me is to have a router with authentication and then use a dealers with go routines to pull the data off. The Channeler approach seems a lot more robust but I can't enable authentication of the external router socket.

**Comment by taotetek** [comment]
I would like to support auth in the channeler.  It's a non trivial amount of work to do so without a large increase in API surface area and / or additional complexity, since the socket needs to be created in the goroutine that also creates the poller, or else Bad Things (TM) happen.

This probably means either adding additional *WIthAuth constructors (which I don't like, as I feel increasing constructor arguments in order to pass more socket options is a bad pattern), or modifying the interaction between the two channels so that socket options can be passed over the push / pull pipe between them.

At the moment, I don't have the time to set aside for the work that would need to be done.

**Comment by arodland** [comment]
I also have an interest in this (as well as the ability to set options like heartbeat or TCP keepalive on the Sock used by a channeler). Is there any possibility that the SockOption struct, added since this ticket was last touched, makes the job easier?

**Comment by taotetek** [comment]
thanks for the pr, @arodland !
