### ISSUE TITLE
Error return in listener.NewCertFromFile is hardcoded to nil

### ISSUE THREAD

**Issue by eric-gilbertson** [zeromq/goczmq#144]
Error return in listener.NewCertFromFile is hardcoded to nil. Thus there is no convenient way to tell whether the cert file is valid. In addition, there is no way to check for validity without the possibility of a panic exception being thrown, e.g. there is no IsValid() call. 

Suggest checking the cert returned from C.zcert_load() for validity and returning an error if not e.g:

// NewCertFromFile Load loads a Cert from files  <--- Cert.go#49
func NewCertFromFile(filename string) (*Cert, error) {
    cert := C.zcert_load(C.CString(filename))
    return &Cert{
        zcertT: cert,
    }, nil  <-- return error if cert is invalid
}

**Comment by taotetek** [comment]
@eric-gilbertson Thanks for the issue report!  There is definitely work that needs to be done around the Cert API that I haven't gotten to yet.  The Go layer should do checks to make sure the cert exists and looks like a correct zcert before it makes any calls to the C layer.

At the moment, since zcert_load itself either asserts or returns, and returns no error codes ( see https://github.com/zeromq/czmq/blob/master/src/zcert.c#L211 ) there is an error return that's hardcoded to nil.  Once I get a little time, I'll add more logic to the go layer that will detect issues before calling to C, and the error return will be utilized.  If anyone else gets to this before me and sends a PR that would be great as well of course!

Cheers,
Brian

**Comment by taotetek** [comment]
Fixed!
