### ISSUE TITLE
Sock io.ReadWriter can't handle len(p) < Frame

### ISSUE THREAD

**Issue by mengzhuo** [zeromq/goczmq#157]
io.Reader read bytes count is wrong
https://github.com/zeromq/goczmq/blob/master/sock.go#L342
You can see it just return the Frame size, not how many bytes are read into p

We can add such code into testcases for validation.
```go
err = dealerSock.SendFrame([]byte("Hello"), FlagNone)
if err != nil {
    t.Errorf("dealerSock.SendFrame failed: %s", err)
}

b = make([]byte, 2)
n, err = routerSock.Read(b)
if n != 2 {
    t.Errorf("routerSock.Read expected 2 bytes read %d", n)  // routerSock.Read expected 2 bytes read 5
}
```

**Comment by taotetek** [comment]
@mengzhuo thanks for the issue report! If someone else doesn't get to fixing this sometime this week, I can get to it next weekend if not before then.

**Comment by taotetek** [comment]
@mengzhuo I've fixed the incorrect byte count returned ( see: https://github.com/zeromq/goczmq/pull/161 ).  For the moment, len(p) < len(frame) will still return an ErrSliceFull error, but the returned count from the Read call is now correct.

I'm thinking over options for how I want to move forward on allowing the Read call accept multiple calls to read from the same frame, in cases where len(p) < len(frame).  This is an interesting issue since it would involve wanting to maintain some context between Read calls (keeping the frame, along with where we are in the frame in our reads) that we currently don't keep.  It's certainly doable and I'll do some experiments to see what approach I like best and is the least intrusive to how the Sock API works in general.  I'll leave this ticket open.

**Comment by taotetek** [comment]
@mengzhuo this weekend I'm going to take a stab at a new type, along the lines of goczmq.Channeler, that will wrap any socket, and provide io.ReadWriter along with the necessary message caching to allow the case of len(p) < len(Frame).
